### PR TITLE
Make tests run without listening

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by jasisk** [comment]
Needs fixing on 0.10 but, otherwise, :+1:

**Comment by pvenkatakrishnan** [comment]
why does it fail only on 0.10 ?

**Comment by aredridel** [comment]
Looks like `shot` and express sometimes don't play nice. Argh.

**Comment by aredridel** [comment]
Rewritten entirely, and based on #54

**Comment by jasisk** [comment]
Ephemeral port! :+1:

**Comment by aredridel** [comment]
Yeah, good enough!

**Comment by pvenkatakrishnan** [comment]
:+1:

**Pull request merged**
